export const GET_USERS = 'GET_USERS';
export const USER_DETAILS = 'USER_DETAILS';
export const LOADING_USERS = 'LOADING_USERS';
export const LOADING_USER_SELECTED = 'LOADING_USER_SELECTED';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
export const GET_EXTENDED_WEATHER = 'GET_EXTENDED_WEATHER';
export const LOADING_CURRENT_WEATHER = 'LOADING_CURRENT_WEATHER';
export const LOADING_EXTENDED_WEATHER = 'LOADING_EXTENDED_WEATHER';